[package]
authors = ['Anonymous']
edition = '2018'
name = 'pallet-template'
version = "2.0.0"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet template for defining custom runtime logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }

[dependencies.frame-support]
default-features = false
version = "2.0.0"
path = "../../../../frame/support"

[dependencies.frame-system]
default-features = false
version = "2.0.0"
path = "../../../../frame/system"

[dependencies.sp-core]
default-features = false
version = "2.0.0"
path = "../../../../primitives/core"

[dependencies.sp-io]
default-features = false
version = "2.0.0"
path = "../../../../primitives/io"

[dependencies.sp-runtime]
default-features = false
version = "2.0.0"
path = "../../../../primitives/runtime"

[dependencies.sp-std]
default-features = false
version = "2.0.0-rc6"
path = "../../../../primitives/std"

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'sp-io/std',
	'sp-std/std',
]
